### ISSUE TITLE
How to execute bash command in commit_message

### ISSUE THREAD

**Issue by hisham-zadfresh** [Automattic/action-commit-to-branch#10]
@dereksmart 
I want my commit message to contain a bash script to get a value from a file, is it doable?

Something like this
```yaml
- name: Push to staging branch
   uses: Automattic/action-commit-to-branch@master
   with:
     branch: 'staging'
     commit_message: ${ echo "Increase version to $(sed -rn 's/^version=([^\n]+)$/\1/p' file.properties)"}
```
