### ISSUE TITLE
Failed to adjust OOM score for shim: invalid argument error

### ISSUE THREAD

**Issue by pedrog-ciandt** [Automattic/action-commit-to-branch#12]
We have been facing the following issue while applying action-commit-to-branch recently:

`  io.containerd.runc.v2: failed to adjust OOM score for shim: set shim OOM score: write /proc/244/oom_score_adj: invalid argument`

After some brief investigation, we have seen some recently problems related to Docker Dind version 20. It may help to take a look into the related similar problems Links. 

** Github Action Code:**

```
      - name: Push fmt changes to PR branch
        if: steps.fmt.outputs.stdout != ''
        uses: Automattic/action-commit-to-branch@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: ${{ github.head_ref }}
          commit_message: 'Apply fmt changes'
```

**Full Github Action Logs:**

If necessary I can provide Full Github Action Log Files.

**Related similar problems**

https://github.com/containerd/containerd/issues/4837
https://discourse.drone.io/t/docker-build-failures-from-oom-score-adjustments/8492/2
